# Generated by Django 4.2 on 2023-04-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_song_alter_post_options_playcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
