# Generated by Django 4.2 on 2023-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_song_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playcount',
            old_name='plays_count',
            new_name='play_count',
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
