# Generated by Django 4.2 on 2023-04-26 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_plays_count_playcount_play_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
